### ISSUE TITLE
Year 2101 problem

### ISSUE THREAD

**Issue by hia3** [Neon22/sun-angle#3]
Given latitude = 0, longitude = 100

    2100-Dec-31 23:55:00
    your azimuth: 113.222
    noaa azimuth: 113.23
    difference: 113.23 - 113.222 = 0,008

    2101-Jan-01 00:00:00
    your azimuth: 113.2
    noaa azimuth: 113.29
    difference: 113.29 - 113.2 = almost 0,1

In other words, error in azimuth between this algorithm and noaa increases >10x in 5 minutes passed between 2100-Dec-31 23:55:00 and 2101-Jan-01 00:00:00.

Problem is in `calc_time`, consider:

    for y in range(2098, 2103):
        print(calc_time(y, 12, 31, 23, 55, 0) - calc_time(y, 12, 31, 23, 50, 0))
        print(calc_time(y+1, 1, 1, 0, 0, 0) - calc_time(y, 12, 31, 23, 55, 0), "\n")

will print:

    0.00347
    0.00347

    0.00347
    0.00347

    0.00347
    1.00347

    0.00347
    0.00347

    0.00347
    0.00347

**Comment by Neon22** [comment]
Hmmm. amazed you found this. exhaustive testing ?
I'm looking into it

**Comment by JagKing** [comment]
In `calc_time` the issue is caused in the calculating the number of leap years, here:
```
    leap = delta // 4 # former leapyears
```
It counts any year divisable by 4, even if it is also divisable by 100 and not 400.  This will cause an incorrect jullian date after 2100 by 1 day and one additional day for the passing of any such year (unless I'm mistaken).

**Comment by Neon22** [comment]
Brilliant. Thanks
